import subprocess

with open('report.html', 'r', encoding='utf-8') as f:
    html = f.read()

# 1. Bigger section labels
html = html.replace(
    '.sec-label{font-size:9px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:rgba(255,255,255,.28);margin-bottom:16px}',
    '.sec-label{font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:rgba(255,255,255,.55);margin-bottom:16px}'
)

# 2. Bigger page title and subtitle
html = html.replace(
    'h1{font-size:32px;font-weight:700;color:#fff;line-height:1.2;margin-bottom:10px}',
    'h1{font-size:40px;font-weight:700;color:#fff;line-height:1.2;margin-bottom:12px}'
)
html = html.replace(
    '.subtitle{font-size:15px;color:rgba(255,255,255,.7);line-height:1.7;max-width:620px;margin-bottom:48px}',
    '.subtitle{font-size:17px;color:rgba(255,255,255,.75);line-height:1.7;max-width:640px;margin-bottom:48px}'
)

# 3. Bigger tool card headings and text
html = html.replace(
    '.tool-card h3{font-size:13px;font-weight:700;color:#fff;margin-bottom:6px}',
    '.tool-card h3{font-size:16px;font-weight:700;color:#fff;margin-bottom:8px}'
)
html = html.replace(
    '.tool-card p{font-size:12px;color:rgba(255,255,255,.72);line-height:1.65}',
    '.tool-card p{font-size:14px;color:rgba(255,255,255,.75);line-height:1.7}'
)
html = html.replace(
    '.tool-badge{font-size:9px;font-weight:700;letter-spacing:1px;text-transform:uppercase;padding:3px 10px;border-radius:10px;margin-bottom:10px;display:inline-block}',
    '.tool-badge{font-size:10px;font-weight:700;letter-spacing:1px;text-transform:uppercase;padding:5px 14px;border-radius:10px;margin-bottom:12px;display:inline-block}'
)
html = html.replace(
    '.win{font-size:10px;font-weight:700;margin-top:10px;padding-top:10px;border-top:1px solid rgba(255,255,255,.07);color:rgba(255,255,255,.28);letter-spacing:.5px;text-transform:uppercase}',
    '.win{font-size:11px;font-weight:700;margin-top:12px;padding-top:12px;border-top:1px solid rgba(255,255,255,.1);color:rgba(255,255,255,.45);letter-spacing:.5px;text-transform:uppercase}'
)

# 4. Bigger slide nav buttons
html = html.replace(
    '.slide-nav-btn{background:rgba(255,255,255,.08);border:none;color:rgba(255,255,255,.6);cursor:pointer;padding:5px 14px;border-radius:16px;font-size:11px;font-weight:600;transition:all .15s}',
    '.slide-nav-btn{background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.2);color:#fff;cursor:pointer;padding:8px 22px;border-radius:20px;font-size:13px;font-weight:600;transition:all .15s}'
)
html = html.replace(
    '.slide-counter{font-size:11px;color:rgba(255,255,255,.35);letter-spacing:.5px}',
    '.slide-counter{font-size:13px;color:rgba(255,255,255,.6);letter-spacing:.5px;font-weight:600}'
)
html = html.replace(
    '.slide-nav{background:rgba(0,0,0,.4);border-bottom:1px solid rgba(255,255,255,.07);display:flex;align-items:center;justify-content:space-between;padding:10px 16px}',
    '.slide-nav{background:rgba(0,0,0,.5);border-bottom:1px solid rgba(255,255,255,.1);display:flex;align-items:center;justify-content:space-between;padding:14px 20px}'
)

# 5. Bigger verdict text
html = html.replace(
    '.verdict-box p{font-size:13px;color:rgba(255,255,255,.78);line-height:1.78}',
    '.verdict-box p{font-size:15px;color:rgba(255,255,255,.82);line-height:1.8}'
)

# 6. Bigger source items
html = html.replace(
    '.src-item a{font-size:12px;color:rgba(255,255,255,.68);text-decoration:none;line-height:1.6}',
    '.src-item a{font-size:13px;color:rgba(255,255,255,.72);text-decoration:none;line-height:1.6}'
)
html = html.replace(
    '.src-item .stitle{font-size:13px;font-weight:600;color:#fff;margin-bottom:2px}',
    '.src-item .stitle{font-size:15px;font-weight:700;color:#fff;margin-bottom:4px}'
)

# 7. Fix audio section - add SoundCloud embed
html = html.replace(
    '''  <div class="audio-section" style="flex-direction:column;gap:16px">
    <div style="display:flex;align-items:center;gap:16px">
      <div class="audio-icon">🎙</div>
      <div>
        <h3 style="font-size:16px;font-weight:700;color:#fff;margin-bottom:4px">Audio overview — Taking control of human evolution</h3>
        <p style="font-size:12px;color:rgba(255,255,255,.45)">Generated by NotebookLM · Hosted on SoundCloud</p>
      </div>
    </div>
    <iframe width="100%" height="120" scrolling="no" frameborder="no" allow="autoplay"
      src="https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/jean-grey-262620260/taking_control_of_human_evolut&color=%231D9E75&inverse=true&auto_play=false&show_user=false&show_comments=false&show_reposts=false&show_teaser=false"
      style="border-radius:10px;margin-top:12px">
    </iframe>
    </div>
  </div>''',
    '''  <div class="audio-section" style="flex-direction:column;gap:20px;align-items:stretch">
    <div style="display:flex;align-items:center;gap:18px">
      <div class="audio-icon" style="width:56px;height:56px;font-size:26px">🎙</div>
      <div>
        <h3 style="font-size:18px;font-weight:700;color:#fff;margin-bottom:6px">Taking control of human evolution</h3>
        <p style="font-size:13px;color:rgba(255,255,255,.55)">AI audio overview generated by NotebookLM · Hosted on SoundCloud</p>
      </div>
    </div>
    <iframe width="100%" height="140" scrolling="no" frameborder="no" allow="autoplay"
      src="https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/jean-grey-262620260/taking_control_of_human_evolut&color=%231D9E75&inverse=true&auto_play=false&show_user=false&show_comments=false&show_reposts=false&show_teaser=false"
      style="border-radius:12px;display:block">
    </iframe>
  </div>'''
)

# 8. Bigger nav links
html = html.replace(
    '.nav-link{padding:5px 16px;border-radius:20px;font-size:11px;font-weight:600;color:rgba(255,255,255,.45);border:1px solid transparent;cursor:pointer;text-decoration:none;transition:all .15s}',
    '.nav-link{padding:7px 20px;border-radius:20px;font-size:12px;font-weight:600;color:rgba(255,255,255,.55);border:1px solid transparent;cursor:pointer;text-decoration:none;transition:all .15s}'
)
html = html.replace(
    '.nav-link.active{color:#1D9E75;border-color:rgba(29,158,117,.4);background:rgba(29,158,117,.1)}',
    '.nav-link.active{color:#1D9E75;border-color:rgba(29,158,117,.5);background:rgba(29,158,117,.12);font-weight:700}'
)

with open('report.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("Report design updated")
subprocess.run(['git', 'add', '.'])
subprocess.run(['git', 'commit', '-m', 'design: bigger text, buttons, headings throughout report page'])
subprocess.run(['git', 'push'])
print("Done - wait 30s then refresh /report")