import subprocess

with open('report.html', 'r', encoding='utf-8') as f:
    html = f.read()

old = '''  <div class="audio-section">
    <div class="audio-icon">🎙</div>
    <div class="audio-info">
      <h3>Audio overview — The Evolution of Humanity</h3>
      <p>A podcast-style brief generated by NotebookLM. An AI host discusses the key findings including the two ancestral populations discovery, the Yunxian 2 skull study, and the implications of conscious evolution. Duration: 1m 49s.</p>
      <a class="audio-link" href="https://notebooklm.google.com/notebook/c40aec28-3852-47ed-8e58-d57f31719273?artifactId=b1ef184c-1877-4d1d-818b-8334e447ccd2" target="_blank">Listen on NotebookLM ↗</a>
    </div>
  </div>'''

new = '''  <div class="audio-section" style="flex-direction:column;gap:16px">
    <div style="display:flex;align-items:center;gap:16px">
      <div class="audio-icon">🎙</div>
      <div>
        <h3 style="font-size:16px;font-weight:700;color:#fff;margin-bottom:4px">Audio overview — Taking control of human evolution</h3>
        <p style="font-size:12px;color:rgba(255,255,255,.45)">Generated by NotebookLM · Hosted on SoundCloud</p>
      </div>
    </div>
    <iframe width="100%" height="120" scrolling="no" frameborder="no" allow="autoplay"
      src="https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/jean-grey-262620260/taking_control_of_human_evolut&color=%231D9E75&inverse=true&auto_play=false&show_user=false&show_comments=false&show_reposts=false&show_teaser=false"
      style="border-radius:10px;overflow:hidden">
    </iframe>
  </div>'''

if old in html:
    html = html.replace(old, new)
    print("Audio section updated with SoundCloud embed")
else:
    print("ERROR: Could not find audio section to replace")
    print("Searching for audio-section...")
    idx = html.find('audio-section')
    if idx >= 0:
        print("Found at index", idx)
        print(html[idx-20:idx+200])

with open('report.html', 'w', encoding='utf-8') as f:
    f.write(html)

subprocess.run(['git', 'add', '.'])
subprocess.run(['git', 'commit', '-m', 'feat: embed SoundCloud audio player in report'])
subprocess.run(['git', 'push'])
print("Done - wait 30s then check /report")