import subprocess

with open('report.html', 'r', encoding='utf-8') as f:
    html = f.read()

# Replace the audio placeholder section with a clean link card
old = '''  <div class="audio-section">
    <div class="audio-icon">🎙</div>
    <div class="audio-info">
      <h3>Audio overview — The Evolution of Humanity</h3>
      <p>A podcast-style summary generated by NotebookLM from the research sources. Two AI hosts discuss the key findings, contested claims, and implications of the 2025 discoveries.</p>
      <a class="audio-link" id="audio-link" href="#" target="_blank">Listen on NotebookLM ↗</a>
      <p class="audio-placeholder">Paste your NotebookLM share link — open your notebook, click Share on the Audio Overview, copy the link, and replace the href above in report.html</p>
    </div>
  </div>'''

new = '''  <div class="audio-section">
    <div class="audio-icon">🎙</div>
    <div class="audio-info">
      <h3>Audio overview — The Evolution of Humanity</h3>
      <p>A podcast-style brief generated by NotebookLM. An AI host discusses the key findings including the two ancestral populations discovery, the Yunxian 2 skull study, and the implications of conscious evolution. Duration: 1m 49s.</p>
      <a class="audio-link" href="https://notebooklm.google.com/notebook/c40aec28-3852-47ed-8e58-d57f31719273?artifactId=b1ef184c-1877-4d1d-818b-8334e447ccd2" target="_blank">Listen on NotebookLM ↗</a>
    </div>
  </div>'''

if old in html:
    html = html.replace(old, new)
    print("Audio section updated")
else:
    print("Could not find audio section - may already be updated")

with open('report.html', 'w', encoding='utf-8') as f:
    f.write(html)

subprocess.run(['git', 'add', '.'])
subprocess.run(['git', 'commit', '-m', 'feat: add NotebookLM audio link to report'])
subprocess.run(['git', 'push'])
print("Done - wait 30s then check /report")